### ISSUE TITLE
XFCE: Cannot get the theme applied to windows

### ISSUE THREAD

**Issue by cooljpeg** [luigifab/human-theme#13]
Hey there!

I'm running Xubuntu 20.04 and am not able to get the theme to apply to any windows after installing via PPA. The themes simply don't show up in the Window Manager, and I even tried some of the manual installation methods as well to no avail. This probably isn't an issue on part of the theme, I just don't know what I could be missing and would appreciate any guidance.

Thank you so much! :+}

**Comment by luigifab** [comment]
Can you run the following command and paste the result to check the installation of the theme?
`ls -l /usr/share/themes`

**Comment by cooljpeg** [comment]
Sure thing!

> total 112
drwxr-xr-x  4 root root 4096 Aug 19 03:34  Adwaita
drwxr-xr-x  4 root root 4096 Aug 19 03:34  Adwaita-dark
drwxr-xr-x  3 root root 4096 Aug 19 03:33  Bright
drwxr-xr-x  3 root root 4096 Aug 19 03:37  Daloa
drwxr-xr-x  6 root root 4096 Aug 19 03:37  Default
drwxr-xr-x  3 root root 4096 Aug 19 03:37  Default-hdpi
drwxr-xr-x  3 root root 4096 Aug 19 03:37  Default-xhdpi
drwxr-xr-x  4 root root 4096 Aug 19 03:34  Emacs
drwxr-xr-x 10 root root 4096 Aug 19 03:34  Greybird
drwxr-xr-x  3 root root 4096 Aug 19 03:34  Greybird-accessibility
drwxr-xr-x  3 root root 4096 Aug 19 03:34  Greybird-bright
drwxr-xr-x  3 root root 4096 Aug 19 03:34  Greybird-compact
drwxr-xr-x  9 root root 4096 Aug 19 03:34  Greybird-dark
drwxr-xr-x  3 root root 4096 Aug 19 03:34  Greybird-dark-accessibility
drwxr-xr-x  4 root root 4096 Aug 19 03:34  HighContrast
drwxr-xr-x  6 root root 4096 Dec 21 22:53  human-theme
drwxr-xr-x  5 root root 4096 Dec 21 22:53  human-theme-blue
drwxr-xr-x  5 root root 4096 Dec 21 22:53  human-theme-green
drwxr-xr-x  5 root root 4096 Dec 21 22:53  human-theme-orange
drwxr-xr-x  3 root root 4096 Aug 19 03:37  Kokodi
drwxr-xr-x  3 root root 4096 Aug 19 03:37  Moheli
drwxr-xr-x 11 root root 4096 Aug 19 03:37  Numix
drwxr-xr-x  3 root root 4096 Aug 19 03:34  Raleigh
drwxr-xr-x  3 root root 4096 Aug 19 03:33  Retro
drwxr-xr-x  3 root root 4096 Aug 19 03:33  Smoke
drwxr-xr-x  3 root root 4096 Dec 21 18:43  Yaru
drwxr-xr-x  3 root root 4096 Dec 21 18:43  Yaru-dark
drwxr-xr-x  3 root root 4096 Aug 19 03:33 'ZOMG-PONIES!'

**Comment by luigifab** [comment]
I tried to install the theme via PPA package, and it works for me.

![xfce](https://user-images.githubusercontent.com/31816829/147220983-58dbc47a-a6fa-4c88-be86-704b25b0de4e.png)

Not sure why this does not work for you.

**Comment by cooljpeg** [comment]
Hmm, weird!

Is there a way I can uninstall the theme and reinstall it? And is there a way I can restore all of my system's theming to default maybe? I was playing around with Gnome Tweaks and it didn't seem to make any changes whatsoever, so I'm worried something is wrong with my system in that regard. I'm new to theming so sorry for the silly questions, but thank you for your help! :+}

**Comment by luigifab** [comment]
You can uninstall the package, and remove themes in `~/.themes/` directory.
But if you are using Xfce with Xubuntu, you must use `xfce4-appearance-settings` to set windows theme.

**Comment by cooljpeg** [comment]
Just uninstalled and reinstalled the package, used Appearance Settings to change the theme, and still the same issue. I also just noticed in the screenshot you posted that the windows still don't reflect the screenshots in the README (the font, the styling, the icons, etc), it only affects the colors and in-program buttons it seems.

Maybe I worded my initial issue wrong; it's that the window bars aren't using the right fonts, styles, or icons. Is there an additional step I must take to enable these final touches? Window Manager doesn't list the Human themes at all, and that application seems to be the thing that changes the Window styles.

Thank you for bearing with me, I really appreciate it and value your work in reviving this theme for modern use. :+}

**Comment by luigifab** [comment]
Thank you. I'm glad to see I'm not alone who loves this old theme.

I understood. My screenshots are created with Mate, and Marco/Metacity window theme.
For XFCE, this is **xfwm**, so the window theme does not work. For now, you can install **clearlooks-phenix-theme** to [get it works](https://github.com/jpfleury/clearlooks-phenix/tree/master/xfwm4), run `xfwm4-settings` to select window theme.

Edit: preview of the future:
![image](https://user-images.githubusercontent.com/31816829/148693255-8b52c5dd-0eb1-47df-82a9-8cab30f69e63.png)

**Comment by luigifab** [comment]
Fixed in v2.0.0.
