### ISSUE TITLE
Generating Human-Theme variants with custom colors?

### ISSUE THREAD

**Issue by johnsonmt01** [luigifab/human-theme#18]
Is there a script to generate custom versions of this Human Theme based on a specific color hex?

For example, I'd like to create themes based on the Ubuntu accent color options:
https://itsfoss.com/accent-color-ubuntu/

Thank you.

**Comment by luigifab** [comment]
No, but this is easy.
The blue, orange and green variants use symlinks to all files except for _gtk-3.0/gtk.css_.
You can easily create new versions by editing colors in this file.

Then run _svg.sh_ to regenerate svg files.

**Comment by johnsonmt01** [comment]
Thank you, I'll give it a try.

**Comment by Cassyette-Tape** [comment]
I don't mean to necro post this, but the svg.sh doesn't seem to regen the svg files anymore. Every attempt I've made to do this leads to a GTK theme with missing svg's being generated.

**Comment by luigifab** [comment]
Yes, the script doesn't create files, it only update files.
For example, if you change `theme_base` color, all SVG that contains `theme_base` will be updated.
But if you remove SVG files, SVG are not created.
