### ISSUE TITLE
Mate volume indicator missing

### ISSUE THREAD

**Issue by mbndr** [luigifab/human-theme#19]
Hello
I'm using the theme with Debian and Mate desktop (love it so far).
I just realized that the volume indicator (when using the Fn keys) is not displaying as it should (same with for example brightness indicator).

How it is:
![image](https://user-images.githubusercontent.com/7734369/231869610-c2edefdb-ef89-40a8-93fd-dc95fe1bcce0.png)

How it should be (screenshot with Menta theme):
![image](https://user-images.githubusercontent.com/7734369/231869722-c66e0230-822c-4238-80c0-509882277b82.png)

Not very critical but I thought I open an issue.
Keep up the good work!

**Comment by luigifab** [comment]
Thanks, you are right, this is fixed for the next release:

![volume](https://user-images.githubusercontent.com/31816829/231875784-184c569b-9c2b-4d77-ac23-953e4340c3ff.png)

**Comment by mbndr** [comment]
Thank you, looks great :)
